# Generated by Django 5.2.5 on 2026-03-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='payment_transaction_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
