# Generated by Django 5.2.5 on 2026-03-24 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_payment_request_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_transactions', to='core.paymentrequest'),
        ),
    ]
