# Generated by Django 5.2.5 on 2026-03-24 22:05

from django.db import migrations, models


def backfill_withdrawal_wallet_earning(apps, schema_editor):
    PaymentRequest = apps.get_model('core', 'PaymentRequest')
    PaymentRequest.objects.filter(type='withdraw').update(withdrawal_wallet_type='earning')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction_payment_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='withdrawal_wallet_type',
            field=models.CharField(blank=True, choices=[('earning', 'Earning wallet'), ('topup', 'Top-up wallet')], default='', max_length=20),
        ),
        migrations.RunPython(backfill_withdrawal_wallet_earning, migrations.RunPython.noop),
    ]
