# Generated by Django 5.2.5 on 2026-03-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_cod_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidrecord',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('esewa', 'Esewa'), ('khalti', 'Khalti'), ('bank', 'Bank'), ('cod', 'Cash on Delivery'), ('wallet', 'Wallet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('esewa', 'Esewa'), ('khalti', 'Khalti'), ('bank', 'Bank'), ('cod', 'Cash on Delivery'), ('wallet', 'Wallet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payoutaccount',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'Esewa'), ('khalti', 'Khalti'), ('bank', 'Bank'), ('cod', 'Cash on Delivery'), ('wallet', 'Wallet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='receivedrecord',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('esewa', 'Esewa'), ('khalti', 'Khalti'), ('bank', 'Bank'), ('cod', 'Cash on Delivery'), ('wallet', 'Wallet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('esewa', 'Esewa'), ('khalti', 'Khalti'), ('bank', 'Bank'), ('cod', 'Cash on Delivery'), ('wallet', 'Wallet')], max_length=20),
        ),
    ]
