# Generated by Django 5.2.5 on 2026-04-05 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_systemsetting_app_android'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='push_notifications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receivers', models.ManyToManyField(blank=True, related_name='push_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
