# Generated by Django 5.2.5 on 2026-04-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_push_notification_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='kind',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='high_value_payment_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='If > 0, staff get ADMIN_A9 when a deposit/withdraw request amount is >= this value.', max_digits=12),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
