# Generated by Django 5.2.5 on 2026-04-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sales_deferred_rewards_salesitem_credited'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.CharField(blank=True, help_text='Province (प्रदेश); stored on Address.state for delivery.', max_length=100),
        ),
    ]
