from django.urls import path
from core.views.admin import (
    dashboard_views,
    user_views,
    kyc_views,
    payout_account_views,
    vendor_views,
    deposit_views,
    withdrawal_views,
    category_views,
    product_views,
    campaign_views,
    submission_views,
    package_views,
    purchase_views,
    sales_views,
    transaction_views,
    setting_views,
    activity_log_views,
    city_views,
    shipping_charge_views,
    address_views as admin_address_views,
    paid_record_views,
    received_record_views,
    banner_views,
    site_settings_views as admin_site_settings_views,
    cms_page_views,
    analytics_views,
    sms_log_views,
    push_notification_views,
)

urlpatterns = [
    path('dashboard/', dashboard_views.admin_dashboard),
    path('pending-counts/', dashboard_views.pending_counts),
    path('users/', user_views.user_list),
    path('users/<int:pk>/', user_views.user_detail_update),
    path('kyc/', kyc_views.kyc_list),
    path('kyc/<int:user_id>/approve/', kyc_views.kyc_approve),
    path('kyc/<int:user_id>/reject/', kyc_views.kyc_reject),
    path('payout-accounts/', payout_account_views.payout_account_list),
    path('payout-accounts/<int:pk>/', payout_account_views.payout_account_detail),
    path('payout-accounts/<int:pk>/approve/', payout_account_views.payout_account_approve),
    path('payout-accounts/<int:pk>/reject/', payout_account_views.payout_account_reject),
    path('vendors/', vendor_views.vendor_list_create),
    path('vendors/<int:pk>/', vendor_views.vendor_detail_update),
    path('deposits/', deposit_views.deposit_list),
    path('deposits/<int:pk>/', deposit_views.deposit_detail),
    path('deposits/<int:pk>/approve/', deposit_views.deposit_approve),
    path('deposits/<int:pk>/reject/', deposit_views.deposit_reject),
    path('withdrawals/', withdrawal_views.withdrawal_list),
    path('withdrawals/<int:pk>/', withdrawal_views.withdrawal_detail),
    path('withdrawals/<int:pk>/approve/', withdrawal_views.withdrawal_approve),
    path('withdrawals/<int:pk>/reject/', withdrawal_views.withdrawal_reject),
    path('system-withdrawals/', withdrawal_views.system_withdrawal_list),
    path('system-withdrawals/<int:pk>/approve/', withdrawal_views.system_withdrawal_approve),
    path('system-withdrawals/<int:pk>/reject/', withdrawal_views.system_withdrawal_reject),
    path('system-withdrawals/<int:pk>/', withdrawal_views.system_withdrawal_detail),
    path('categories/', category_views.category_list_create),
    path('categories/<int:pk>/', category_views.category_detail_update_delete),
    path('products/', product_views.product_list_create),
    path('products/reorder-page/', product_views.product_reorder_page),
    path('products/<int:pk>/', product_views.product_detail_update_delete),
    path('campaigns/', campaign_views.campaign_list_create),
    path('campaigns/<int:pk>/', campaign_views.campaign_detail_update_delete),
    path('submissions/', submission_views.submission_list),
    path('submissions/<int:pk>/', submission_views.submission_detail),
    path('submissions/<int:pk>/approve/', submission_views.submission_approve),
    path('submissions/<int:pk>/reject/', submission_views.submission_reject),
    path('packages/', package_views.package_list_create),
    path('packages/<int:pk>/', package_views.package_detail_update_delete),
    path('purchases/', purchase_views.purchase_list),
    path('purchases/<int:pk>/', purchase_views.purchase_detail),
    path('sales/', sales_views.sales_list),
    path('sales/<int:pk>/', sales_views.sales_detail),
    path('sales/<int:pk>/status/', sales_views.sales_status_update),
    path('transactions/', transaction_views.transaction_list),
    path('transactions/<int:pk>/', transaction_views.transaction_detail),
    path('settings/', setting_views.setting_detail_update),
    path('activity-logs/', activity_log_views.activity_log_list),
    path('sms-logs/', sms_log_views.sms_log_list),
    path('cities/', city_views.city_list_create),
    path('cities/<int:pk>/', city_views.city_detail_update_delete),
    path('shipping-charges/', shipping_charge_views.shipping_charge_list_create),
    path('shipping-charges/<int:pk>/', shipping_charge_views.shipping_charge_detail_update_delete),
    path('addresses/', admin_address_views.address_list_create),
    path('addresses/<int:pk>/', admin_address_views.address_detail_update_delete),
    path('paid-records/', paid_record_views.paid_record_list_create),
    path('paid-records/<int:pk>/', paid_record_views.paid_record_detail_update_delete),
    path('received-records/', received_record_views.received_record_list_create),
    path('received-records/<int:pk>/', received_record_views.received_record_detail_update_delete),
    path('banners/', banner_views.banner_list_create),
    path('banners/<int:pk>/', banner_views.banner_detail_update_delete),
    path('site-settings/', admin_site_settings_views.site_settings),
    path('cms-pages/', cms_page_views.cms_page_list_create),
    path('cms-pages/<int:pk>/', cms_page_views.cms_page_detail_update_delete),
    path('push-notifications/resolve-phones/', push_notification_views.push_notification_resolve_phones),
    path('push-notifications/', push_notification_views.push_notification_list_create),
    path('push-notifications/<int:pk>/send-chunk/', push_notification_views.push_notification_send_chunk),
    path('push-notifications/<int:pk>/', push_notification_views.push_notification_detail_update_delete),
    # Analytics
    path('analytics/overview/', analytics_views.analytics_overview),
    path('analytics/users/', analytics_views.analytics_users),
    path('analytics/sales/', analytics_views.analytics_sales),
    path('analytics/products/', analytics_views.analytics_products),
    path('analytics/vendors/', analytics_views.analytics_vendors),
    path('analytics/procurement/', analytics_views.analytics_procurement),
    path('analytics/affiliates/', analytics_views.analytics_affiliates),
    path('analytics/campaigns/', analytics_views.analytics_campaigns),
    path('analytics/finance/', analytics_views.analytics_finance),
    path('analytics/behaviour/', analytics_views.analytics_behaviour),
    path('analytics/retention/', analytics_views.analytics_retention),
    path('analytics/intelligence/', analytics_views.analytics_intelligence),
    path('analytics/sms/', analytics_views.analytics_sms),
]
