from django.urls import path
from core.views.client_area import (
    notification_views,
    fcm_views,
    dashboard_views,
    profile_views,
    kyc_views,
    payout_account_views,
    address_views,
    wallet_views,
    payment_request_views,
    product_views,
    category_views,
    package_views,
    campaign_views,
    submission_views,
    order_views,
    transaction_views,
    referral_views,
    wishlist_views,
    shipping_charge_views,
)

urlpatterns = [
    path('notifications/unread-count/', notification_views.notification_unread_count),
    path('notifications/mark-all-read/', notification_views.notification_mark_all_read),
    path('notifications/mark-all-unread/', notification_views.notification_mark_all_unread),
    path('notifications/<int:pk>/read/', notification_views.notification_mark_read),
    path('notifications/<int:pk>/unread/', notification_views.notification_mark_unread),
    path('notifications/', notification_views.notification_list),
    path('fcm-token/', fcm_views.fcm_token_register),
    path('dashboard/', dashboard_views.client_dashboard),
    path('profile/', profile_views.profile_me_update),
    path('kyc/', kyc_views.kyc_status_submit),
    path('payout-accounts/', payout_account_views.payout_account_list_create),
    path('payout-accounts/<int:pk>/', payout_account_views.payout_account_detail_delete),
    path('addresses/', address_views.address_list_create),
    path('addresses/<int:pk>/', address_views.address_detail_update_delete),
    path('wallet/', wallet_views.wallet_balance),
    path('shipping-charges/', shipping_charge_views.shipping_charge_list),
    path('payment-requests/', payment_request_views.payment_request_list_create),
    path('products/', product_views.product_list),
    path('products/sections/', product_views.product_list_sections),
    path('products/<int:pk>/', product_views.product_detail),
    path('products/<slug:slug>/', product_views.product_detail_by_slug),
    path('categories/', category_views.category_list),
    path('packages/', package_views.package_list),
    path('packages/<int:pk>/', package_views.package_detail),
    path('campaigns/', campaign_views.campaign_list),
    path('campaigns/<int:pk>/', campaign_views.campaign_detail),
    path('submissions/', submission_views.submission_list_create),
    path('submissions/<int:pk>/proofs/', submission_views.submission_proof_create),
    path('submissions/<int:pk>/', submission_views.submission_detail),
    path('orders/', order_views.order_list),
    path('orders/<int:pk>/', order_views.order_detail),
    path('transactions/', transaction_views.transaction_list),
    path('referrals/', referral_views.referral_list),
    path('team-tree/', referral_views.team_tree),
    path('wishlist/', wishlist_views.wishlist_list_add),
    path('wishlist/ids/', wishlist_views.wishlist_ids),
    path('wishlist/<int:product_id>/', wishlist_views.wishlist_remove),
]
